### PR TITLE
fix(ui): DateRanger allowClear should work 

### LINKED ISSUE #919: [Bug]: DateRanger missing deletion function
### Describe the bug

DateRanger missing deletion function，To add a deletion similar to antd
image
image

### Environment

0.4.6

### Fast reproduce steps

-

### Expected behavior

_No response_

### Actual behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by linhf123**
### 📦 Modified package

- [ ] @oceanbase/design
- [x] @oceanbase/ui
- [ ] @oceanbase/icons
- [ ] @oceanbase/charts
- [ ] @oceanbase/util
- [ ] @oceanbase/codemod
- [ ] Other (about what?)

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / documentation update
- [ ] Demo update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Bundle size optimization
- [ ] Performance optimization
- [ ] Enhancement feature
- [ ] Internationalization
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Workflow
- [ ] Other (about what?)

### 🔗 Related issue link

close #919

### 💡 Background and solution
| Before | After |
| :--- | :--- |
| image| imageimage|

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | -  support clear        |
| 🇨🇳 Chinese | - 🐞 修复 DateRanger `allowClear` 不生效的问题。   |

### ☑️ Self-Check before Merge

⚠️ Please check all items below before requesting a reviewing. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Tests is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

File: packages/ui/src/DateRanger/demo/locale.tsx [hunk 1]
```diff
@@ -33,7 +33,7 @@ export default () => {
       </div>
       <ConfigProvider locale={locale}>
         <Space direction="vertical">
-          <DateRanger />
+          <DateRanger allowClear />
```
Comment (dengfuping) [inline packages/ui/src/DateRanger/demo/locale.tsx:36]: 没有看到 `allowClear` 相关的改动，原先不支持透传 `allowClear` 吗？

**Review by dengfuping — CHANGES_REQUESTED** [review]

File: packages/ui/src/DateRanger/demo/locale.tsx (hunk 1 above)
Comment (linhf123) [reply packages/ui/src/DateRanger/demo/locale.tsx:36]: 原先通过 `pointer-events: none` 给禁用了默认的 picker 事件，`clear` 一直不会被触发，现在放开了做了下兼容

Comment (dengfuping) [reply packages/ui/src/DateRanger/demo/locale.tsx:36]: 放开之后会起止时间可以分别触发面板，期望表现是一个整体:

Comment (linhf123) [reply packages/ui/src/DateRanger/demo/locale.tsx:36]: 覆盖了下默认样式，让交互呈现是一整个的感觉
image
